apiVersion: v2
name: network
description: A Helm chart for a blockchain network on Kubernetes
type: application
version: 2.0.0-beta.6
appVersion: 2.0.0-beta.6
maintainers:
  - name: SettleMint
    email: support@settlemint.com
    url: https://settlemint.com
dependencies:
  - name: network-bootstrapper
    version: 2.0.0-beta.6
  - name: network-nodes
    version: 2.0.0-beta.6
