apiVersion: v2
name: redis
description: A simple Redis deployment for development environments
type: application
version: 2.0.0-beta.6
appVersion: 2.0.0-beta.6
icon: https://redis.io/docs/about/images/redis-logo.png
maintainers:
  - name: SettleMint
    email: support@settlemint.com
    url: https://settlemint.com
