# Node Information
genesis-file="/opt/besu/genesis.json"
logging="INFO"
node-private-key-file="/opt/besu/key"

# Database
data-storage-format="FOREST"
bonsai-limit-trie-logs-enabled=false
data-path="/opt/besu/data"
cache-last-blocks=1024

# Transaction Pool
min-gas-price=1000000000
tx-pool="SEQUENCED"
tx-pool-max-size=100000
tx-pool-no-local-priority=true
tx-pool-limit-by-account-percentage=1.0
tx-pool-enable-save-restore=true

# P2P network - ENABLED for QBFT
p2p-enabled=true
discovery-enabled=false
p2p-interface="0.0.0.0"
p2p-port=30303
max-peers=25
rpc-tx-feecap=0
sync-min-peers=0
sync-mode="FULL"
remote-connections-limit-enabled=false
random-peer-priority-enabled=true
receipt-compaction-enabled=true

# Mining - ENABLED for block production
miner-enabled=true
miner-coinbase="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

# HTTP Access
host-allowlist=["*"]

# JSON-RPC API
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["DEBUG","ETH","ADMIN","WEB3","IBFT","NET","TRACE","EEA","PRIV","QBFT","PERM","TXPOOL","PLUGINS"]
rpc-http-cors-origins=["all"]
rpc-http-authentication-enabled=false
revert-reason-enabled=true
rpc-http-max-active-connections=2000
rpc-ws-max-active-connections=2000
rpc-http-max-request-content-length=524288000
rpc-ws-max-frame-size=2097152
rpc-http-max-batch-size=512

# GRAPHQL-RPC API
graphql-http-enabled=true
graphql-http-host="0.0.0.0"
graphql-http-port=8547
graphql-http-cors-origins=["all"]

# WebSockets API
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546
rpc-ws-api=["DEBUG","ETH","ADMIN","WEB3","IBFT","NET","TRACE","EEA","PRIV","QBFT","PERM","TXPOOL","PLUGINS"]
rpc-ws-authentication-enabled=false

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545
metrics-category=["BLOCKCHAIN","ETHEREUM","EXECUTORS","JVM","NETWORK","PEERS","PROCESS","PRUNER","RPC","SYNCHRONIZER","TRANSACTION_POOL"]