global:
  besuGenesis:
    generation:
      enabled: true

besu-validator-1:
  enabled: true
  fullnameOverride: besu-node-validator-1

besu-validator-2:
  enabled: false
  fullnameOverride: besu-node-validator-2

besu-validator-3:
  enabled: false
  fullnameOverride: besu-node-validator-3

besu-validator-4:
  enabled: false
  fullnameOverride: besu-node-validator-4

besu-rpc-1:
  enabled: true
  fullnameOverride: besu-node-rpc-1
  node:
    besu:
      account:
        password: "password"

besu-rpc-2:
  enabled: false
  fullnameOverride: besu-node-rpc-2
  node:
    besu:
      account:
        password: "password"
